# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d66917097575a4ad4e5d5450785cecc1f7faf1953a9495890600ee234523bb01d968ca6c6c2c876a1d4a720d103541b12e1585358d67521ed19f3be7b00ed978

test:
  secret_key_base: e2e93750942162f7a8b94f83b4d56f5137a453e6b6824bf504f06829652e5ba6a2964f16eae3402cfcceb2fbb1a51ad7319b9c77182801b90c9027e8d9ccf495

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
